services:
  postgres:
    image: postgres:latest
    container_name: user-service-postgres
    ports:
      - 5432:5432
    env_file:
      - ../.env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512m
          cpus: "1"
        reservations:
          memory: 256m
          cpus: "0.2"
    networks:
     - user-service-network

  redis:
    image: redis:latest
    container_name: user-service-redis
    ports:
      - 6379:6379
    env_file:
      - ../.env.example
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512m
          cpus: "1"
        reservations:
          memory: 256m
          cpus: "0.2"
    networks:
     - user-service-network

  user-service:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile.dev
    container_name: user-service
    ports:
      - "8080:8080"
    env_file:
      - ../.env.example
    volumes:
      - ../:/app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512m
          cpus: "1"
        reservations:
          memory: 256m
          cpus: "0.2"
    networks:
     - user-service-network

networks:
  user-service-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: