app:
  name: user-service
  port: 8080

postgres:
  host: user-service-postgres-srv
  port: 5432
  db: db
  user: user
  password: password
  tz: Asia/Shanghai

redis:
  host: user-service-redis-srv
  port: 6379
  password: password

