apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-{{ .Values.postgres.storage.pvc_name }}
spec:
  storageClassName: {{ .Values.app.name }}-{{ .Values.postgres.storage.classname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.name }}-{{ .Values.postgres.storage.pv_name }}
spec:
  storageClassName: {{ .Values.app.name }}-{{ .Values.postgres.storage.classname }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  hostPath:
    path: {{ .Values.postgres.storage.path }}
    type: DirectoryOrCreate